### ISSUE TITLE
time recentering in pomper_salientme issue

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#10]
pomper_salientme appears to have a shifted timecourse, suggesting that something went wrong in the re-centering process. I suspect this has something to do with the rezeroing issue in the resampling function in peekds https://github.com/langcog/peekds/issues/35

**Comment by mzettersten** [comment]
confirmed issue and implemented temporary fix

**Comment by lingerxu** [comment]
In https://github.com/langcog/peekbank-data-import/blob/master/data/pomper_salientme/import_scripts/import.R
Starting line 298, point_of_disambiguation was set to 0 before resampling and comments indicate assumed centered t, so this is where the shift came from.
