### ISSUE TITLE
attword_processed misclassifies some items as familiar

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#16]
Target labels appear to have been drawn from the image names in attword_processed. 

Conjecture, to be confirmed with further detective work: This leads to an issue in a case where a novel item (labeled dax or modi) carries a name ("balls") that is misinterpreted as its (English) target label. Images carrying the name "skwish" and "balls" should be treated as novel items, and we should figure out their respective novel labels (dax or modi) in each instance.

**Comment by adriansteffan** [comment]
Balls is now classified as "novel" and no longer a label, only appearing as the base image for both labels "dax" and "modi"
