### ISSUE TITLE
Templates need to be updated to reflect stimuli table schema change

### ISSUE THREAD

**Issue by lingerxu** [langcog/peekbank-data-import#17]
Both icoder and smi templates were made before the stimuli table schema change

**Comment by cbergey** [comment]
Do you just mean the addition of image_description and image_description_source, or is there another change? (The templates were made after the change in how we split rows, but the changes don't apply to the datasets used in the templates.)

**Comment by lingerxu** [comment]
I meant the addition. When I look through the scripts while working on kartushina_2009, I did not find the new fields, image_description and image_description_source. A very small issue, but I just want to make a note there.

**Comment by mzettersten** [comment]
resolving for now, made a new issue that we need to update all templates to the 2024 schema
