### ISSUE TITLE
attword_processed misclassifies some novel trials as familiar

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#19]
In attword_processed, one of the novel images is informally called "balls" (since they are balls stacked on top of each other). This leads to an issue at import where these trials are erroneously classified as familiar trials with the target label "balls", when in fact these are novel label trials (e.g. the label provided is dax). 

This should be updated/ corrected in the import script.

**Comment by mcfrank** [comment]
Oooh is that messing up our aoa analysis?
-- 
Mike

**Comment by mzettersten** [comment]
I don't think so, because it really only affects one item (the one with the target label "balls") that is systematically misclassified in one dataset. But we would probably want to make sure to remove that item from any item-level analyses until the database gets updated.
