### ISSUE TITLE
month rounding inconsistent across datasets

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#20]
We're currently inconsistent about how we round months (to whole months, to a certain number of decimal places, no rounding, etc.).

For example, in reflook_socword, original lab units are in decimal years, we multiply by 12, and then round to the nearest whole month.

In attword_processed, original lab units are also in decimal years, we also multiply by 12, but do not do any rounding.

Minor, not terribly consequential inconsistency, but worth smoothing out at some point.

**Comment by lingerxu** [comment]
Thank you for noticing this! We have two fields, lab_age and age - both of which are float fields. Although I always like data with more precision, it is convenient to have age as a rounded field for easier analysis and visualization. Let's decide in the next meeting.

**Comment by mzettersten** [comment]
Yes - to be clear, the column I'm referring to above is "age" - the standardized column that we convert lab_age values into

**Comment by adriansteffan** [comment]
What did you decide on in the end?
It would make sense to document that and then either go through all datasets and fix it or put it on the code review checklist

**Comment by mzettersten** [comment]
Let’s put it on the code review checklistOn May 22, 2024, at 2:38 PM, Adrian Steffan ***@***.***> wrote:﻿
What did you decide on in the end?
It would make sense to document that and then either go through all datasets and fix it or put it on the code review checklist

**Comment by adriansteffan** [comment]
Decision for now is no rounding at all, I will go through the datasets and have a look

**Comment by mzettersten** [comment]
Do you mean there was a decision for no decimal rounding? are we sure we want to lose that information? We probably don't want to treat 6.9 months the same as 6.0 months, I would say, 1 month is consequential, especially at our younger age ranges.

**Comment by adriansteffan** [comment]
I have checked all the datasets and fixed the ones that were still rounding. The code review will give this another check, and we will eventually abstract away age calculation in the IDless import format
