### ISSUE TITLE
update all datasets to conform to Aug 15-19 2022 schema changes

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#24]
All past datasets should be updated and double-checked as conforming to the new schema. 
Checklist below.
- [ ] casillas_tseltal_2015
- [x] ronfard_2021
- [x] perry_cowpig
- [ ] pomper_yumme
- [ ] pomper_saffran_2016
- [ ] weisleder_stl
- [x] adams_marchman_2018
- [ ] newman_genderdistractor
- [ ] pomper_salientme
- [x] fmw_2013
- [ ] xsectional_2007
- [x] swingley_aslin_2002
- [ ] kartushina_2019
- [x] reflook_v4 (formerly reflook_v1)
- [ ] reflook_socword (formerly reflook_v3)
- [x] potter_remix
- [x] potter_canine
- [ ] newman_sinewave
- [ ] hurtado_2008
- [ ] attword_processed
- [ ] garrison_bergelson_2020
- [x] mahr_coartic
- [x] byers-heinlein_2017
- [ ] bacon_gendercues
- [ ] frank_tablet_2016

**Comment by adriansteffan** [comment]
Outdated, we are now tracking these to the gh issues and the dataset table - and have an ongoing migration to 2024 anyway. Closing to tidy up the gh issues
