### ISSUE TITLE
double-check updating of all past datasets to match Aug 15-19 2022 schema changes

### ISSUE THREAD

**Issue by mzettersten** [langcog/peekbank-data-import#25]
We should also double-check/review all edits to past datasets made during the updating process.
Checklist below:

- [ ] casillas_tseltal_2015
- [ ] ronfard_2021
- [ ] perry_cowpig
- [ ] pomper_yumme
- [ ] pomper_saffran_2016
- [ ] weisleder_stl
- [ ] adams_marchman_2018
- [ ] newman_genderdistractor
- [ ] pomper_salientme
- [ ] fmw_2013
- [ ] xsectional_2007
- [x] swingley_aslin_2002
- [ ] kartushina_2019
- [ ] reflook_v4 (formerly reflook_v1)
- [ ] reflook_socword (formerly reflook_v3)
- [ ] potter_remix
- [ ] potter_canine
- [ ] newman_sinewave
- [ ] hurtado_2008
- [ ] attword_processed
- [ ] garrison_bergelson_2020
- [ ] mahr_coartic
- [ ] byers-heinlein_2017
- [ ] bacon_gendercues
- [ ] frank_tablet_2016

**Comment by adriansteffan** [comment]
I guess we are now tracking these through the dataset table and the github issues - we also have a new schema. I am closing this to tidy up the gh issues.
