### ISSUE TITLE
Decide on CDI to LWL matching

### ISSUE THREAD

**Issue by alvinwmtan** [langcog/peekbank-data-import#29]
Some datasets have CDIs and LWLs that were not administered at the same time, and that may not have the same number of administrations (e.g., 4x CDI admins vs 3x LWL admins).

Currently, for such datasets (e.g., fernald_marchman_2012), for each CDI admin we find the LWL admin that matches closest in age, breaking ties downwards. This means that 
1. When there are "extra" CDI admins, they are nonetheless matched to an LWL admin; and
2. There might be some bunching of admins (e.g., if there are CDI admins at 18 and 21mo + LWL admins at 18 and 24mo, both CDI admins will get matched to the 18mo LWL admin instead of "spreading" them out evenly across LWL admins).

We should decide whether this is an acceptable policy or if an alternative is preferable.

**Comment by adriansteffan** [comment]
I think this issue is outdated, so I am closing it

-> the new 2024 schema puts cdi on the subjects table, so no matching is needed
