### ISSUE TITLE
SMI datasets to import 

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekbank-data-import#3]
could add:

* erica yoon simpimp: https://github.com/ejyoon/simpimp/tree/master/eye-tracking - @ejyoon it looks like there is no info about which item is associated with which trial, though? the control trials are probably informative for peekbank
* ann nordmeyer data from https://www.sciencedirect.com/science/article/pii/S0749596X14001028 - not sure if these are high priority

**Comment by ejyoon** [comment]
@mcfrank just added item info to simpimp/eye-tracking/info/simpimp_et_order.csv

**Comment by mcfrank** [comment]
thank you Erica!!

**Comment by adriansteffan** [comment]
Added the yoon simpimp data to osf and created an issue to track it

@mcfrank Can the ann nordmeyer data be found online? I took a brief look and didn't find anything, but I might have missed it

**Comment by mcfrank** [comment]
nordmeyer data are available here: https://drive.google.com/drive/folders/1UbGrZPVQlAlL6PZa3NGYT26a-yaS8krg?usp=sharing

Note that this is the original archival folder. The readme explains that only "version 5" is published in the paper, and that's the one we should import. it's represented in the paper as two experiments, but was run as a single package. please feel free to tag me with comments if you have questions.

**Comment by adriansteffan** [comment]
Turns out, has been a prior import attempt for nordmeyer already, discussion continues in the relevant issue https://github.com/langcog/peekbank-data-import/issues/60
