### ISSUE TITLE
[garrison_bergelson_2020] too many trial_type_ids

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#30]
I am new to the schema, so it might be best to have someone else look at this before I go and change the script:

It seems this import script broke when it got ported to a new schema - creating more trial types than necessary.

This is the affected code: https://github.com/langcog/peekbank-data-import/blob/master/data/garrison_bergelson_2020/import_scripts/import.R#L106C1-L125C35

It seems that unique trial_types entry is created for every trial of every participant. Shouldn't trial types be independent of both subject and trial? Happy to have more opinions on this!

**Comment by mzettersten** [comment]
Yes trial_types should be independent of subject and trial, i.e. there should in general be fewer trial types than trials (though they could be identical if specific trial types only occur once.

**Comment by kalenkovich** [comment]
In this experiment, the parent heard the phrase in the headphones and then repeated them out loud to the child. This setup led to almost no identical points of disambiguation and thus almost as many different trial types as there were trials. Moore & Bergelson 2022 Verbs has the same problem, albeit for a different reason. In both cases, it is possible to redefine the trial start to be x ms before the target word onset which would lead to a smaller set of meaningful trial types. I would then put EyeLink's trial start in trials.trial_aux_data.

**Comment by mzettersten** [comment]
I'm not sure I can fully visualize the solution Zhenya, but my hunch is to leave the variable points of disambiguation and bite the bullet in having a large number of trial types (almost identical with total trial numbers). It doesn't "cost" us too much to do this for this one dataset, and that perhaps keeps things a bit more consistent with representations in other datasets. I'm a bit worried about putting critical information for understanding the trial structure in aux data, especially if this would only apply to a couple of datasets (seems like it increases the chance that something could be misinterpreted).

**Comment by adriansteffan** [comment]
The issue in the script was not the trial types being numerous due to the varying points of disambiguation, but due to the Participant ID being part of the grouping that determined "unique" trial types. This was most likely introduced when scripts were changed to accommodate trial IDs being unique between participants (by accident applying the same constraint to the trial type ids)

From a glance at it, there shouldn't be a big difference as the variety introduced by the varying PODs makes this "accidentally" true for this dataset, but I pushed a fix so that the code follows the column schema and is more robust against future changes in that area
