### ISSUE TITLE
[gazetriggered_2020] - CDI Data Issues

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#31]
The cdi data here is a bit incomplete, how do I handle these fields:

instrument_type - This was not reported, the authors only stated they used N-CDI, which offers all 3 instruments - do we just email the authors in these cases?

percentile - This is not in the data, how are missing values represented in the json? null?

language - I know it is dutch,  but I don’t know the wordbank language format and wordbank.stanford.edu won’t load for me for some reason. Do we have another document for this?

**Comment by mzettersten** [comment]
We now have a doc for Wordbank format: https://docs.google.com/spreadsheets/d/1EcQnUgwLfVBrBqwuUcP7HrF0v_h_oHuAVX2tKlmfweo/edit?usp=sharing

for stuff where we don't have data (like if there isn't percentile info), we just do not include the key-value pair in the json

**Comment by adriansteffan** [comment]
Just saving this for future reference on cdi instrument type

As a general rule (thanks to Alvin and Martin): wg is the younger one, and usually has 2 positive value options (understands, understands and says) whereas ws only has one

**Comment by adriansteffan** [comment]
Worked these into the script
