### ISSUE TITLE
[gazetriggered_2020] What is "familiarity" referring to?

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#34]
The “vanilla_trial” column info states vanilla trials include familiar words.
(the stimulus novelty column on the stimuli also requires information on the familiarity of the stimulus)

Does this familiarity refer to

A) the experiment design, i.e. is the word INTENDED to be familiar/novel by the researchers

B) the infant itself, i.e. is the word known to the SPECIFIC INFANT, as determined by a CDI

if B) is the case, I would need to go back and create two versions of every trial_type and stimulus, and cross-reference them with the CDI data gathered on the infant to assign the correct one to each trial.
This could be a bit inconsistent, though, as this data is unlikely to exist for all datasets.

How has this been handled so far?

**Comment by mzettersten** [comment]
Good question. Closer to (A). We wouldn't want to make it (B) for several reasons, but one straightforward one is that to do what you suggest, we don't need an extra column, that is something users could compute from the CDI data (if it exists) themselves.

Originally, this column is meant to distinguish words that are designed to be familiar to infants (real words that are normatively expected to be known by kids - this is true of the standard LWL task). Novel was meant to indicate stimuli that are made-up novel words w/ unfamiliar objects (e.g., a labeling a weird dog toy a toma, classic novel word learning designs). But there are certainly cases that don't fall cleanly into these two groups - (familiar image, but novel word; real word and image, but just very hard for an infant/ essentially novel - e.g., antelope; etc.). 

I think basically we want to treat all familiar object-word pairings normatively expected to be known by the child in the age range, from the perspective of the experimenter, as familiar - everything else should be novel. We might consider a more fine-grained characterization at some point, but this seems like the most practically important distinction.
