### ISSUE TITLE
dubious import decisions - Moore & Bergelson 2022

### ISSUE THREAD

**Issue by kalenkovich** [langcog/peekbank-data-import#38]
Copied from [readme.txt](data/moore_bergelson_2022/import_scripts/readme.txt):

> 4. Importing decisions
> 
>     # Stimuli
> 
>     When creating the stimuli table, we defined a target stimulus to be a combination of:
> 
>     - Label (verb). This includes the pronunciation. So, “jump” and “joomp” are considered to be different labels.
>     - Carrier phrase. This information was redundant with the label information in this experiment.
>     - Image (video) associated with the label. There is a “jump” video but there isn’t a separate “joomp” video.
> 
>     For example, label "joomp" spliced into "Look! She can ..." and the associated "jump" video constitute one target stimulus which we will label as "jump_can-joomp" in the "lab_stimulus_label" column.
> 
>     Distractors, however, don't have a label or a carrier phrase associated with them and so there isn’t an obvious target stimulus we could assign to represent them. We could have arbitrarily selected one of the two target stimuli that use the same video; for example, the one with the correctly pronounced verb. Instead, we added distractors as separate stimuli and gave them labels like “jump_distractor”.
> 
>     # Trial types
> 
>     The target word onset time varied considerably between trials. Because of that, we ended up with as many trial types as there were trials.
> 
>     # AOI region sets
> 
>     Points with x coordinate 640 were assigned to the “left” AOI, and with 640.1 and above - to the right AOI. To represent that in the table, we would need to set r_x_min to 640.1 or any other number larger than 640 and not larger than 640.1. The table columns are interger, however, so we could either go with 640 or 641. We went with 640.

**Comment by mzettersten** [comment]
These are great, thanks Zhenya!!

Here are some to-dos, @adriansteffan:
- make sure that carrier phrase isn't included in the stimulus table
- give distractors their canonical names (stimuli are not differentiated between target and distractor)

AOI and trial types decisions seem good.

**Comment by kalenkovich** [comment]
I have a question about the stimuli names.

> * give distractors their canonical names (stimuli are not differentiated between target and distractor)

In this experiment, a single video can play three different roles: target with correctly pronounced label, target with incorrectly pronounced label, and distractor (no audio). Here is how I represented it in the stimuli table (I dropped the columns that have the same values across all three rows):

| original_stimulus_label | english_stimulus_label | stimulus_novelty | lab_stimulus_id  | stimulus_id |
|-------------------------|------------------------|------------------|------------------|-------------|
| clean                   | clean                  | familiar         | clean_can-clean  | 0           |
| cline                   | cline                  | novel            | clean_can-cline  | 1           |
| NA                      | NA                     | familiar         | clean_distractor | 2           |


Because of the added dimension of correctly/incorrectly pronounced audio, I don't think it is possible to collapse these three rows into one. Or is this not what you are suggesting?

**Comment by adriansteffan** [comment]
Fixed the stimulus table and updated the cdi format to match v2024
