### ISSUE TITLE
[ronfard_2021] needs double-checking (& upload)

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#42]
I have updated the json formatting for the cdi & lui data and moved it to the subjects table. The output should now match the latest version of our schema.

The changes were small, so they should be quick to check: 61b738903407d59e640d35f459f925ea40fe3773

A few open questions for this and future cdi data:

1. wsshort was administered, can I assume that version always tests comprehension (only)?

2. If the English version of the MacArthur-Bates CDI or its shortform is administered, can I assume that the language is American English?

3. The database table states "pending receipt from researcher", but there is no mention of any missing data in the code - what info do we still need?

**Comment by adriansteffan** [comment]
Added a small fix in b2f2d8988a51d54c64ec3215a46ceb5a979e565d

**Comment by mzettersten** [comment]
1. No, wsshort should only test *production* (does that contradict anything in the data?)

Just double-checked the paper:

> The CDI short form (Fenson et al., 2007) consisted of 100 word items and asked
parents to identify the words their children produce. 

2. Based on where the data was collected (Harvard), yes!

3. I assume that is outdated - we had to follow up for info about distractors iirc.

**Comment by adriansteffan** [comment]
2 & 3 Alright! 

1: Nope, that was an oversight on my part
