### ISSUE TITLE
[casillas_tseltal_2015] Import script in repo missing local changes + osf error

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#43]
I think someone already did the work and updated the import script to match the new format (most likely Ruthe), as Ruthe uploaded new processed data with the new "aux" columns to OSF in February. Two things still need to happen to finalize the import:

1. The changes have not been committed to the import script in the repo: https://github.com/langcog/peekbank-data-import/blob/master/data/casillas_tseltal_2015/import_scripts/import.R

2. On OSF, both the "stimulus.csv" and "subjects.csv" seem to contain the stimulus table, likely just a typo when saving the files.

(already contacted Ruthe to see if she still has her changes)

**Comment by mzettersten** [comment]
@adriansteffan Let me know if you are still waiting to hear back from Ruthe, I can follow up!

**Comment by adriansteffan** [comment]
Still waiting on the uploaded script, needed to close https://github.com/langcog/peekbank-data-import/issues/4

**Comment by adriansteffan** [comment]
Fixed it, passes strict validator now!
