### ISSUE TITLE
[newman_genderdistractor] Update import script to match 2024 schema

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#46]
Mostly: Move aux Data to subjects aux table

**Comment by adriansteffan** [comment]
This is a weird one, as LDS and MCDI scores are there for some participants in the demographic file, but not a single one of these participants has corresponding eye tracking data (!). Maybe we should ask the lab about this again, or have a deeper look at what is happening here with more context?

**Comment by mzettersten** [comment]
@JMankewitz could you take a look when you next get a chance?

**Comment by adriansteffan** [comment]
fix (16mo added) and add cdi data (wgshort comp most probably)

**Comment by adriansteffan** [comment]
Fixed all remaining issues, (strict) validator is happy now! There are 2 minor decision todos that need to be checked and transferred to the readme, but that can be done during the code review
