### ISSUE TITLE
[potter_remix] Update import script to match 2024 schema

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#51]
Aux columns there, need to add CDI data from OSF

**Comment by adriansteffan** [comment]
I imported the cdi data, however, there are still open points before I upload the data. The provided data only contains a single raw score for cdi with no explanation.

If I didn't miss it, there is no information on the language, instrument type and measure used here, the provided docx is vague and the published paper does not mention the cdi. 

@mzettersten you mentioned that you know a bit more about the potter studies, any thoughts?

**Comment by mzettersten** [comment]
I think it's Words and Sentences in the child's dominant language. See p. 4 of the paper:

> In addition to being interviewed about their child's language ex‐ posure, parents filled out (a) the Spanish and English versions of the MacArthur-Bates Communicative Development Inventory: Words and Sentences (MCDI; Fenson et al., 2007; Jackson‐Maldonado et al., 2003) to assess children's vocabulary knowledge, (b) the Language Mixing Scale (Byers‐Heinlein, 2013) to measure children's exposure to mixed‐language utterances, and (c) basic demographic question‐ naires. Parents of all participants provided demographic informa‐ tion and estimates of children's global exposure to English versus Spanish, but only 16 parents provided MCDI data in the child's dom‐ inant language (M = 237 words produced, SD = 176, range: 57–611), 14 parents provided MCDI data in the child's non‐dominant language (M = 90 words, SD = 79, range: 17–264), and 18 parents completed the Language Mixing Scale (M = 17, SD = 8.6, range: 0–30).

**Comment by mzettersten** [comment]
looks like the cdi column has 16 data points, hence my assumption that it's the dominant language. If I'm interpreting correctly, this is kinda awkward because it means that it's sometime spanish ws and sometimes english ws, depending on the column English_Percent (>50 means english ws, spanish ws otherwise.

I'll try to track down the original data.

**Comment by mzettersten** [comment]
@adriansteffan ok I found a summarized CDI data file on OSF with both dominant and non-dominant language CDI and added it to Peekbank (comparing columns suggests my interpretation above was correct, but we might as well import both spanish and english summarized WS from this file.

Leaving myself a note that we can add the raw CDI responses if desired (will just take some puzzling on the Baby Lab server).

**Comment by adriansteffan** [comment]
Added the cdi data for both spanish and english to the subject aux data (in case the specific language existed for a given participant)
