### ISSUE TITLE
[potter_canine] Update import script to match 2024 schema

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#53]
Aux columns there, need to add CDI data from OSF

**Comment by adriansteffan** [comment]
I added imports for the cdi data, but there are 2 problems:

1. measure, language and instrument_type are not apparent from the data (maybe I am missing something)

2. The cdi data IDs (202-251) and the looking data IDs (101-145) have no overlap at all, making the import of cdi data rather pointless. Any ideas what happened here @mzettersten?

**Comment by mzettersten** [comment]
1. It should be the English WS MCDI production. See the paper here: https://www.cambridge.org/core/journals/journal-of-child-language/article/frequent-vs-infrequent-words-shape-toddlers-realtime-sentence-comprehension/C0A6CEEA6BA8A3DC3D880185DEA9F7FD

2. There's actually two datasets, Canine (Canine.n36.raw.txt) and Canine2 (canine2_rawLookingTimeData.n34). Previously only the first dataset was imported, but we should also import the new, second one. The paper actually only reports on that second dataset, and the CDI data that we have so far is also only for that second dataset. There's also CDI data for the first, but I need to do some detective work to find it. So, two to-dos:

- [ ] extend import script to import both datasets.
- [ ] find the CDI data for the first dataset (Canine)

**Comment by mzettersten** [comment]
@adriansteffan Ok, I got us the summarized CDI data for Canine (the first version).

Leaving myself a note that i can get the raw CDIs if needed, but will require a gluing together some data from the server.

**Comment by adriansteffan** [comment]
I added the CDI and the second dataset - I was able to just throw it into the same pipeline as the old datasets due to the similarity of the two datasets (only differing in columns that were cut off anyway)
