### ISSUE TITLE
reflook_v3 has "manu1" as an item

### ISSUE THREAD

**Issue by mcfrank** [langcog/peekbank-data-import#6]
any thoughts on what this means? should it be "manu"?

**Comment by cbergey** [comment]
there are trials in which there are "two manus" on the screen (manu1 and manu2), so the numbers were kept to differentiate the stimuli.

**Comment by mcfrank** [comment]
thanks for following up... i don't recall that trial type - that sounds
odd! @dyurovsky do you remember this?

**Comment by mcfrank** [comment]
figured it out - this was socword and those were trials that had some ME content to them.
