### ISSUE TITLE
[borovksy_2019] update to 2024 schema

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#62]
The script itself is in 3.0 schema - but there seems to be no data for this on osf (also there might be cdi import missing from the script, can't tell without data)

**Comment by mzettersten** [comment]
Check out the paper's open OSF page: https://osf.io/4vdgu/. Any data that was worked on would have been taken from there. If we think the data is useable for Peekbank, then we should add that raw data to Peekbank's OSF.

**Comment by mzettersten** [comment]
Data is now on OSF!

**Comment by adriansteffan** [comment]
Check if there is cdi data on osf and update the code if needed (once osf wakes up from its slumber)

**Comment by adriansteffan** [comment]
There seems to be CDI data, so we need to import that

**Comment by adriansteffan** [comment]
Done!
