### ISSUE TITLE
[yurovsky_2017] What is up with this dataset?

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#68]
The import script is 4 years old, it is not part of the dataset google sheet

There seems to be some data on osf, but it is difficult to interpret

**Comment by adriansteffan** [comment]
@mzettersten Once again invoking your insider info

**Comment by mzettersten** [comment]
Yeah this turns out to be attword_processed. I think we should just delete this residual stuff. I went ahead and removed the data from OSF and deleted the old import script.
