### ISSUE TITLE
Automated ID sanity checks

### ISSUE THREAD

**Issue by adriansteffan** [langcog/peekbank-data-import#70]
With multiple people working on the import scripts over time combined with schema migrations, I think there are bound to be some issues with how the foreign key ids are assigned - the validator does some checking, but I already came across some issues that aren't  caught (creating too many trial types, assigning xy to the wrong trial id)

We might want to brainstorm some ways to make sanity checking easier - as checking the joining logic of every import script is tedious  
(showing the total numbers of ids per table, showing orphaned table entries with no id partners etc.)

**Comment by mzettersten** [comment]
yeah, that makes sense - I like the idea of having a function that spits out some general information about the foreign key ids (like your idea of total number, any failed matches across tables; validator should already ensure uniqueness; anything else...?).

This could be directly integrated in the peekds validator function OR it could be a separate function `validate_keys` that we run at the end of the import scripts.

**Comment by adriansteffan** [comment]
Let's think about this during our next meeting along with other validation we come up with in https://github.com/langcog/peekbank-data-import/issues/119

**Comment by adriansteffan** [comment]
discussion moved to the relevant validator/checklist issues
